### PR TITLE
path to main should be lib, not dist

### PR DESCRIPTION
**Pull request by tscizzle**
There seems to be no `dist/` directory. And `lib/` has `textile.js`

### CODE REVIEW

**Comment by alexturpin** [comment]
I just spent quite a while figuring out why I would always get 

     Error: Cannot find module 'textile-js'

When trying to `require('textile-js')`. This is a big problem as it means that the module can not be easily required out the gate after installing npm and can cause quite a few headaches.

Please merge this pull request and update npm @borgar !

**Comment by borgar** [comment]
I am very sorry for the delay. I acknowledge that not only is this amazing brainfart my responsibility, I should have merged and the request and pushed an update out right away.

Relevant commit (for my own records): https://github.com/borgar/textile-js/commit/bfab3046784cf6106e8f3a8387e530556bb27b8a

**Comment by borgar** [comment]
Updated NPM package is live.

**Comment by alexturpin** [comment]
No worries, thank you very much!

**Pull request merged**
