### PR TITLE
Add the option showOriginalLineNumber,

### PR DESCRIPTION
**Pull request by GehDoc**
Add the option showOriginalLineNumber, to map the elements of HTML output, with the line numbers of input text.

### CODE REVIEW

**Comment by GehDoc** [comment]
Hi @borgar ,
I've pushed this (and done a bug report to your repo some months ago), because I'm working on a Textile viewer which needs to synchronize scrolling between the source Textile code, and the visual HTML representation.
Tell me please, if it interests you to integrate my works in your library (yes/no/fix the FIXME before/...), or If you prefer that I continue working on my fork without bothering you !
Best regards

**Comment by GehDoc** [comment]
Nice to see that you are interested by this feature ! I had to stop looking at this after June for personal reasons, and now I'm back on it : Mainly, publishing my work based on it (If you are interested, we can talk about it by mail : see my profile). If you want some help to update your live test page with it, I can do it once you have stabilized the API : I'm not interested in maintaining my fork, and I think it's better when people can rely on only one repository.

My feelings :
- your idea of having the ribbon doing more of the work seems good : it can remove my FIXME (creating a map of : charpos -> offset line) by computing it on the fly. And at the end, getting the total input line numbers.
- I don't like to add loops on data. But, having a mutation step is interesting, if you provide a way to set, through the options, a function hook called at this step. No idea yet, about parameters feeding such a hook, but It may alllow for exemple, to rewrite relative links for a non-web textile editor.

**Comment by craigkovatch** [comment]
Resurrecting a very old thread here :) Did this come close to any kind of completion? We would very much like this feature, too.

**Comment by GehDoc** [comment]
@craigkovatch : you can use the master branch of [my fork](GehDoc/textile-js).
It is up to date with this repo regarding textile language support, but I didn't care much on lintering / packaging, and have no time to polish the solution.

The feature you need is totally operational, tested, and used in the VSCode textile extension published in another repo of my github space.

**Comment by borgar** [comment]
I am working on a much needed update of the library that includes a better parse tree where nodes are tagged with source offsets, making it easy to link output nodes to input lines. I am hoping to be able to release the update around the start of April.

**Comment by craigkovatch** [comment]
@borgar that sounds great! It turns out the fork is not super useful to us because we want to manipulate the textile parse tree, i.e. before it has been transformed to jsonml. Is it possible to hook into this stage somehow? Seems unexposed, even internally, currently.

**Comment by borgar** [comment]
> we want to manipulate the textile parse tree, i.e. before it has been transformed to jsonml.

I am replacing jsonml entirely with a better structure (more akin to HTML DOM elements). For the very reason that I wanted the option to apply transformations to the tree before rendering.

To solve things like #42, you would do something this:

```js
const tree =  textile.parseTree(`"google 2":javascript:alert('XSS')`);
tree.visit(node => {
  if (node.attr.href) {
    node.attr.href = escapeJSUrl(node.attr.href);
  }
});
```


> Is it possible to hook into this stage somehow? Seems unexposed, even internally, currently.

I will get this up here as a pull request asap. The branch is functional but needs more tests and cleanup work. It would be good to get some feedback, so if you want to test then that could be ideal for everyone. 🙂

**Comment by borgar** [comment]
An work-in-progress next version is now accessible: https://github.com/borgar/textile-js/pull/69

**Comment by borgar** [comment]
I'm closing this PR as the #69 supersedes it.

**Pull request closed without merging**
